/**
 * @example pipe(x, f, g) === g(f(x))
 */
export const pipe: Pipe = (value: unknown, ...fns: ((arg: unknown) => unknown)[]) =>
  fns.reduce((acc, fn) => fn(acc), value);

type Pipe = {
  <A>(
    value: A, //
  ): A;
  <A, B>(
    value: A, //
    fn1: (arg: A) => B,
  ): B;
  <A, B, C>(
    value: A, //
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
  ): C;
  <A, B, C, D>(
    value: A, //
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
  ): D;
  <A, B, C, D, E>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
  ): E;
  <A, B, C, D, E, F>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
  ): F;
  <A, B, C, D, E, F, G>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
  ): G;
  <A, B, C, D, E, F, G, H>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
  ): H;
  <A, B, C, D, E, F, G, H, I>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
  ): I;
  <A, B, C, D, E, F, G, H, I, J>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
  ): J;
  <A, B, C, D, E, F, G, H, I, J, K>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
  ): K;
  <A, B, C, D, E, F, G, H, I, J, K, L>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
  ): L;
  <A, B, C, D, E, F, G, H, I, J, K, L, M>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
  ): M;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
    fn13: (arg: M) => N,
  ): N;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
    fn13: (arg: M) => N,
    fn14: (arg: N) => O,
  ): O;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
    fn13: (arg: M) => N,
    fn14: (arg: N) => O,
    fn15: (arg: O) => P,
  ): P;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
    fn13: (arg: M) => N,
    fn14: (arg: N) => O,
    fn15: (arg: O) => P,
    fn16: (arg: P) => Q,
  ): Q;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
    fn13: (arg: M) => N,
    fn14: (arg: N) => O,
    fn15: (arg: O) => P,
    fn16: (arg: P) => Q,
    fn17: (arg: Q) => R,
  ): R;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
    fn13: (arg: M) => N,
    fn14: (arg: N) => O,
    fn15: (arg: O) => P,
    fn16: (arg: P) => Q,
    fn17: (arg: Q) => R,
    fn18: (arg: R) => S,
  ): S;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
    fn13: (arg: M) => N,
    fn14: (arg: N) => O,
    fn15: (arg: O) => P,
    fn16: (arg: P) => Q,
    fn17: (arg: Q) => R,
    fn18: (arg: R) => S,
    fn19: (arg: S) => T,
  ): T;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(
    value: A,
    fn1: (arg: A) => B,
    fn2: (arg: B) => C,
    fn3: (arg: C) => D,
    fn4: (arg: D) => E,
    fn5: (arg: E) => F,
    fn6: (arg: F) => G,
    fn7: (arg: G) => H,
    fn8: (arg: H) => I,
    fn9: (arg: I) => J,
    fn10: (arg: J) => K,
    fn11: (arg: K) => L,
    fn12: (arg: L) => M,
    fn13: (arg: M) => N,
    fn14: (arg: N) => O,
    fn15: (arg: O) => P,
    fn16: (arg: P) => Q,
    fn17: (arg: Q) => R,
    fn18: (arg: R) => S,
    fn19: (arg: S) => T,
    fn20: (arg: T) => U,
  ): U;
};
