/**
 * @example pipe(x, f, g) === g(f(x))
 */
export const pipe: Pipe = (value: unknown, ...fns: ((param: unknown) => unknown)[]) =>
  fns.reduce((acc, fn) => fn(acc), value);

type Pipe = {
  <A>(
    value: A, //
  ): A;
  <A, B>(
    value: A, //
    fn1: (param: A) => B,
  ): B;
  <A, B, C>(
    value: A, //
    fn1: (param: A) => B,
    fn2: (param: B) => C,
  ): C;
  <A, B, C, D>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
  ): D;
  <A, B, C, D, E>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
  ): E;
  <A, B, C, D, E, F>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
  ): F;
  <A, B, C, D, E, F, G>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
  ): G;
  <A, B, C, D, E, F, G, H>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
  ): H;
  <A, B, C, D, E, F, G, H, I>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
  ): I;
  <A, B, C, D, E, F, G, H, I, J>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
  ): J;
  <A, B, C, D, E, F, G, H, I, J, K>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
  ): K;
  <A, B, C, D, E, F, G, H, I, J, K, L>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
  ): L;
  <A, B, C, D, E, F, G, H, I, J, K, L, M>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
  ): M;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
    fn13: (param: M) => N,
  ): N;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
    fn13: (param: M) => N,
    fn14: (param: N) => O,
  ): O;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
    fn13: (param: M) => N,
    fn14: (param: N) => O,
    fn15: (param: O) => P,
  ): P;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
    fn13: (param: M) => N,
    fn14: (param: N) => O,
    fn15: (param: O) => P,
    fn16: (param: P) => Q,
  ): Q;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
    fn13: (param: M) => N,
    fn14: (param: N) => O,
    fn15: (param: O) => P,
    fn16: (param: P) => Q,
    fn17: (param: Q) => R,
  ): R;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
    fn13: (param: M) => N,
    fn14: (param: N) => O,
    fn15: (param: O) => P,
    fn16: (param: P) => Q,
    fn17: (param: Q) => R,
    fn18: (param: R) => S,
  ): S;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
    fn13: (param: M) => N,
    fn14: (param: N) => O,
    fn15: (param: O) => P,
    fn16: (param: P) => Q,
    fn17: (param: Q) => R,
    fn18: (param: R) => S,
    fn19: (param: S) => T,
  ): T;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(
    value: A,
    fn1: (param: A) => B,
    fn2: (param: B) => C,
    fn3: (param: C) => D,
    fn4: (param: D) => E,
    fn5: (param: E) => F,
    fn6: (param: F) => G,
    fn7: (param: G) => H,
    fn8: (param: H) => I,
    fn9: (param: I) => J,
    fn10: (param: J) => K,
    fn11: (param: K) => L,
    fn12: (param: L) => M,
    fn13: (param: M) => N,
    fn14: (param: N) => O,
    fn15: (param: O) => P,
    fn16: (param: P) => Q,
    fn17: (param: Q) => R,
    fn18: (param: R) => S,
    fn19: (param: S) => T,
    fn20: (param: T) => U,
  ): U;
};
